// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orauiykrwnelbqwainiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yYXVpeWtyd25lbGJxd2Fpbml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDYxMjQsImV4cCI6MjA2MTA4MjEyNH0.OCVb8v6vnoWhNYecxzuZqeFF3vqfxTp7_QDowZztgIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);